version: "3.8"

services:

  nginx:
    container_name: nginx
    depends_on:
      - front
    image: nginx:alpine
    restart: 'no'
    user: root
    ports:
      - 8050:80
      - 80:80
      - 443:443
    volumes:
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/default/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    networks:
      - sample-net
    extra_hosts:
      - host.docker.internal:172.17.0.1

  front:
    container_name: front
    image: node:14.18.0-alpine3.14
    tty: true
    volumes:
      - ./app:/app
    entrypoint: ["/bin/sh", "/app/.docker/entrypoint.sh"]
    working_dir: /app
    networks:
      - sample-net
    extra_hosts:
      - host.docker.internal:172.17.0.1
      
networks:
  sample-net:
    name: sample-net
    driver: bridge